##
# IBM Resiliency Orchestration DRM role
#
# Author: F.PERREAU
##

#
# INSTALL PREREQUISIT PACKAGES
#
- name: INSTALL PREREQUISIT PACKAGES 
  dnf:
    name: "{{ PACKAGES }}"
    state: present
  
#
# CONFIGURE LINUX RESOURCES
#
- name: SYSCTL CONFIG FILE
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{item}}"
  with_items:
  - "net.ipv4.tcp_retries2 = 4"
  - "net.ipv4.ip_forward = 1"
  - "net.ipv6.conf.all.disable_ipv6 = 1"
  - "net.ipv6.conf.default.disable_ipv6 = 1"
- name: LIMITS.CONF
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{item}}"
  with_items:
  - "root soft nproc  10240"
  - "root hard nproc  10240"
  - "root soft nofile 20480"
  - "root hard nofile 20480"
  