---
##
# IBM Resiliency Orchestration DRM role
#
# Author: F.PERREAU
##

#
# Configure BUILD server environment
#
- name: CREATE BUILD DIRECTORY
  file:
    path: "{{ BUILD }}"
    state: directory
- name: COPY BINARY FILES
  unarchive:
    src: "{{ FILES }}/{{ item.archive }}"
    dest: "{{ BUILD }}"
    owner: root
    group: root
    mode: "o-xwr"
    creates: "{{ BUILD }}/{{ item.creates }}"
  with_items: "{{ BINARY_FILES }}"
- name: COPY TEMPLATE FILES
  template:
    src: "{{ item }}"
    dest: "{{ BUILD }}/{{ item }}"
  with_items: "{{ TEMPLATE_FILES }}"

#
# Common Linux configuration
#
- name: COMMON LINUX CONFIGURATION
  include_tasks: common.yml

#
# Install MariaDB server
#
- name: INSTALL MARIADB SERVER
  dnf:
    name: "{{ MARIADB_PKG }}"
    state: present
- name: CONFIGURE MY.CNF
  copy:
    src: "{{ BUILD }}/my_drm.cnf"
    dest: "/etc/my.cnf"
    remote_src: true
    backup: true
- name: START MARIADB
  service:
    name: mariadb
    state: started
    enabled: true
- name: SET SQL ROOT PASSWORD
  shell: |
    mysqladmin -u root password '{{ sql_pass }}' &&
    echo 'MariaDB Root password' > {{ BUILD }}/SetSQLRootPassword.lck
  args:
    creates: "{{ BUILD }}/SetSQLRootPassword.lck"

#
# Install Apache TOMCAT
#
- name: INSTALL APACHE TOMCAT
  unarchive:
    src: "{{ TOMCAT_PKG }}"
    dest: /opt
    remote_src: true
    creates: "{{ TOMCAT_HOME }}"
- name: RENAME APACHE TOMCAT HOME
  command: mv /opt/{{ TOMCAT_SRC }} {{ TOMCAT_HOME }}
  args:
    creates: "{{ TOMCAT_HOME }}"

#
# Install Resiliency Orchestration DRM
#
- name: INSTALL PANACES
  command: ./install.bin -f {{ BUILD }}/PanacesServerInstaller.properties
  args:
    chdir: "{{ BUILD }}"
    creates: "{{ EAMSROOT }}"

#
# Install Third PARTY software
#
- name: "INSTALL ThirdPartyJSLib TO {{ item }}/ThirdPartyJSLib/"
  unarchive:
    src: "{{ THIRDPARTY_JSLIB }}"
    dest: "{{ item }}"
    owner: tomcatuser
    group: tomcatusergroup
    remote_src: true
    creates: "{{ item }}/calendar.js"
  with_items:
    - "{{ TOMCAT_HOME }}/webapps/PanacesGUI/scripts"
- name: "COPY ThirPartyJSLib TO {{ item }}"
  copy:
    src: "{{ item }}/ThirdPartyJSLib/"
    dest: "{{ item }}"
    owner: tomcatuser
    group: tomcatusergroup
    remote_src: true
  with_items:
    - "{{ TOMCAT_HOME }}/webapps/PanacesGUI/scripts"
- name: INSTALL GNULIB JSON IN PANACES
  unarchive:
    src: "{{ THIRDPARTY_GNULIB }}"
    dest: "{{ item }}"
    owner: tomcatuser
    group: tomcatusergroup
    mode: "0775"
    remote_src: true
    creates: "{{ item }}/json-20180813.jar"
  with_items:
    - "{{ TOMCAT_HOME }}/webapps/PanacesGUI/WEB-INF/lib"
    - "{{ EAMSROOT }}/lib"

#
# Secure Panaces Tomcat
#
- name: CHANGE TOMCAT CONFIGURATION
  copy:
    src: "{{ BUILD }}/tomcat_conf_server.xml"
    dest: "{{ TOMCAT_HOME }}/conf/server.xml"
    mode: "0640"
    owner: tomcatuser
    group: tomcatusergroup
    remote_src: true
    backup: true

#
# Configure Panaces service
#
- name: SYSTEMCTL PANACES SERVICE
  copy:
    src: "{{ BUILD }}/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    remote_src: true
  with_items:
    - panaces.service
- name: RELOAD SYSTEM SERVICE DB
  systemd:
    daemon_reload: true
- name: ENABLE PANACES SERVICE
  systemd:
    name: panaces
    state: started
    enabled: true

#
# Create Backup Panaces location
#
- name: CREATE BACKUP PANACES LOCATION
  file:
    path: /opt/backup
    owner: panacesuser
    group: "panacesusergroup"
    state: directory

#
# Install Co-Hosted Site Controller
#
- include_tasks: agent_node.yml
  when: drm_mode == "cohosted"
